sudo: required
services:
  - docker
  before_install:
  - docker build -t myopenledgerhub/docker_react -f Dockerfile.dev . 
  script:
  - docker run -t myopenledgerhub/docker_react npm run test -- --coverage